Create event branch mtatiana
Dragos-U/Ema pull request #1
Opened 2023-10-25 15:01 UTC by TatianaMamaliga

2023-10-25 15:43 UTC, Dragos-U commented on src/main/java/ro/itschool/ema/models/dtos/EventDTO.java
> +    @NotNull(message = "Field cannot be null.")
an int variable cannot be Null. either remove the check or change the type to Integer

2023-10-25 15:45 UTC, Dragos-U commented on src/main/java/ro/itschool/ema/models/dtos/EventDTO.java
> +    @Max(value = 10000, message = "Participant number should be less than 10000.")
1) the values could be made Constants
2) without knowing the event type we could not assign these values. these should come from the front end when an Event is created, if restrictions apply. in this case we would have them as variables.

2023-10-25 15:46 UTC, Dragos-U commented on src/main/java/ro/itschool/ema/models/dtos/EventDTO.java
> +    @NotNull(message = "Field cannot be null.")
We can specify exactly which field cannot be null as an error message.

2023-10-25 15:48 UTC, Dragos-U commented on src/main/java/ro/itschool/ema/models/dtos/OrganizerDTO.java
> +    private Date dateOfBirth;
if we care only about the date of birth, without the time, we could use LocalDate

2023-10-25 15:49 UTC, Dragos-U commented on src/main/java/ro/itschool/ema/models/dtos/OrganizerDTO.java
> +    @NotNull(message = "Field cannot be null.")
Maybe we also need @NotEmpty on Strings

2023-10-25 15:50 UTC, Dragos-U commented on src/main/java/ro/itschool/ema/models/dtos/OrganizerDTO.java
> +public class OrganizerDTO implements Serializable {
I am unsure if this is required to be honest. Alex did it, but I have doubts that is useful for us.

2023-10-25 15:52 UTC, Dragos-U commented on src/main/java/ro/itschool/ema/models/dtos/StaffDTO.java
> +public class StaffDTO implements Serializable {
Again, I do not think it is need for REST Api.

2023-10-25 15:53 UTC, Dragos-U commented on src/main/java/ro/itschool/ema/models/dtos/StaffDTO.java
> +    private Date dateOfBirth;
Maybe LocalDate?

2023-10-25 15:56 UTC, Dragos-U commented on src/main/java/ro/itschool/ema/models/dtos/OrganizerDTO.java
> +public class OrganizerDTO implements Serializable {
I thought that the organizer means the organization, not a being having a date of birth. It is like a company organizing events. Let s have a chat about it

2023-10-25 15:57 UTC, Dragos-U commented on src/main/java/ro/itschool/ema/models/entities/Event.java
> +    private Date eventDate;
LocalDateTime?

2023-10-25 15:59 UTC, Dragos-U commented on src/main/java/ro/itschool/ema/models/entities/Event.java
> +@Validated
Validation should be handled at the DTO/service layer

2023-10-25 16:01 UTC, Dragos-U commented on src/main/java/ro/itschool/ema/models/entities/Organizer.java
> +@Inheritance(strategy = InheritanceType.TABLE_PER_CLASS)
could you explain why do you think we need this?

2023-10-25 16:02 UTC, Dragos-U commented on src/main/java/ro/itschool/ema/models/entities/Organizer.java
> +public class Organizer extends User {
Organizer cannot extend User if it is not a human being

2023-10-25 16:15 UTC, Dragos-U commented on src/main/java/ro/itschool/ema/models/entities/User.java
> +    @Column(name = "email")
Maybe have something like this
@Column(name = "email", unique = true)
@Email(message = "Invalid email. Please enter a valid email.")

we need to make sure that the email is unique

2023-10-25 16:24 UTC, Dragos-U commented on src/main/java/ro/itschool/ema/services/StaffServiceImpl.java
> +    Validator validator = factory.getValidator();
do we need manual validation here?

2023-10-25 16:26 UTC, Dragos-U requested changes
Good job. Lots of code. You moved fast. :)
There are some points I would like to discuss about before merging to main when you're available.

2023-10-26 14:26 UTC, Dragos-U requested changes
Minor changes. After done and tested you can directly merge to main.

2023-10-26 14:26 UTC, Dragos-U commented on src/main/java/ro/itschool/ema/models/dtos/OrganizerDTO.java
> -    @NotNull(message = "Field cannot be null.")
as a suggestion, if all error messages are the same, when the error appears we don't know which Field cannot be null. they should be changed to "{VariableName} field cannot be null."

2023-10-26 14:26 UTC, Dragos-U commented on src/main/java/ro/itschool/ema/models/entities/Organizer.java
> +    private String entityName;
why not organizerName?

2023-10-26 14:26 UTC, Dragos-U commented on src/main/java/ro/itschool/ema/models/entities/Organizer.java
> +public class Organizer {
how is the Organizer linked to StaffMembers? Don"t we need a List<StaffMembers>?  we should follow the ERD diagram so that:
@OneToMany(mappedBy ="organizer")
private List<Staff> staffList = new ArrayList<>();

2023-10-26 14:26 UTC, Dragos-U commented on src/main/java/ro/itschool/ema/models/entities/Staff.java
> +
Here we need to link the Staff with the Organizer
@ManyToOne
@JoinColumn(name ="organizer")
private Organizer organizer;

2023-10-27 04:30 UTC, TatianaMamaliga commented on src/main/java/ro/itschool/ema/models/dtos/OrganizerDTO.java
> -    @NotNull(message = "Field cannot be null.")
The field was left on purpose general, as the variable causing the error is mentioned in the log. For a better readability, the variables will be in the validation message.

2023-10-27 13:44 UTC, merged